### ISSUE TITLE
开启界面主题时不显示

### ISSUE THREAD

**Issue by 1zyao** [BalloonUpdate/DynamicLoader#1]
dyn版本：1.0
mcpatch版本：1.10.0

使用dyn启动mcpatch（开启主题）：
![image](https://github.com/BalloonUpdate/DynamicLoader/assets/107829654/770bde7d-c7c9-4685-94c4-4ee5ec68936d)
直接开启mcpatch(开启主题)：
![image](https://github.com/BalloonUpdate/DynamicLoader/assets/107829654/ec712b39-4ead-4071-a57a-dee78b3ead37)
使用dyn启动mcpatch（关闭主题）：
![image](https://github.com/BalloonUpdate/DynamicLoader/assets/107829654/a9321208-b33c-450e-bae0-d8ae9e45cf36)
直接开启mcpatch(关闭主题)：
![image](https://github.com/BalloonUpdate/DynamicLoader/assets/107829654/0e331a1e-ae48-4f68-b617-0b960c998776)

**Comment by 1zyao** [comment]
@HelloTools-bot

**Comment by 1zyao** [comment]
@HelloTools-bot

**Comment by 1zyao** [comment]
@asforest 需要日志之类的吗

**Comment by asforest** [comment]
不需要，我这边能稳定复现

需要点时间修复这个问题

感觉是上游的 JFormDesigner/FlatLaf 库的问题，待验证

**Comment by 1zyao** [comment]
o

**Comment by 1zyao** [comment]
怎么看mcpatch版本号来着

**Comment by asforest** [comment]
这样

![image](https://github.com/BalloonUpdate/DynamicLoader/assets/28993050/6a3d4989-e85e-4520-9a6e-9f91584d7296)

**Comment by 1zyao** [comment]
mcpatch版本1.1.5开启主题可以正常显示

**Comment by asforest** [comment]
从1.1.6开始往后就不行了吗

**Comment by 1zyao** [comment]
没试 我试试去

**Comment by 1zyao** [comment]
1.1.8开始的

**Comment by 1zyao** [comment]
1.1.7还可以显示

**Comment by asforest** [comment]
知道了。因为从1.1.3开始使用独立进行运行的方式去运行以解决限速的问题，而1.1.8的时候默认又换回了1.1.3之前的老启动方式。导致本应该早被暴露的问题隐藏到了现在。

解决方法是删掉客户端jar文件根目录下的.no-standlone-process文件回到新的启动方式。但是代价是会出现一些奇奇怪怪的问题，比如进程残留无法启动mc等（这个问题概率触发，不是必现）

**Comment by 1zyao** [comment]
这个概率是不是大点 我遇到过 除非pcl右下角关闭客户端重新启动 或者任务管理器结束 但是我服务器那堆玩家。。。 我估计手把手教都不一定会

**Comment by asforest** [comment]
这样的话那只能先关闭主题了，虽然美观差点但是功能是正常的

后面看看能不能换UI框架解决这个卡死的问题

**Comment by 1zyao** [comment]
要是更新日志窗口里写关闭窗口时System.exit(0)可行吗

**Comment by asforest** [comment]
双击启动是可行的，但是javaagent启动的时候不行，会连带Mc进行也一起关闭了

1.1.9版本修过一次双击启动进程残留的问题，至于javagent启动会不会有这个问题暂时没有测试过

**Comment by 1zyao** [comment]
如果没有新版本（没有弹出更新窗口）会有概率进程残留

**Comment by asforest** [comment]
是1.1.10版本测试的结果吗

**Comment by 1zyao** [comment]
打错字了 我想问的是”如果没有新版本（没有弹出更新窗口）会有概率进程残留吗“

**Comment by asforest** [comment]
也会有。这个bug不受弹不弹窗口的影响

**Comment by 1zyao** [comment]
谢谢 我做个脚本让他自己循环启动去 看看会不会出现

**Comment by 1zyao** [comment]
试了试 dyn启动mapatch1.1.10没什么问题 启动了大概100次左右没出现

**Comment by asforest** [comment]
issue先关闭了。升级动态加载器到1.1版本即可正常显示主题。如果再次遇到进程残留的问题，烦请单独开启一个issue。
